name: 'setup android sdk for self hosted runner'
description: 'setup-android for self hosted runner'
author: 'amyu'
inputs:
  sdk-version:
    required: false
    description: 'sdk version'
    default: '30'
  build-tools-version:
    required: false
    description: 'build tools version'
    default: '30.0.3'
  ndk-version:
    required: false
    description: 'ndk version'
  cmake-version:
    required: false
    description: 'cmake version'
  cache-disabled:
    required: false
    description: 'disabled cache'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/setup/index.js'
  post: 'dist/cleanup/index.js'
