name: 'build-test'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - name: remove android sdk from ubuntu-latest
        shell: bash
        run: |
          echo 'ANDROID_HOME=' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=' >> $GITHUB_ENV
          rm -rf ~/android

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Setup Android SDK
        uses: ./
        with:
          is-use-cache: true
          sdk-version: '30'
          build-tools-version: '30.0.3'
          cmake-version: '3.10.2.4988404'
          ndk-version: '23.1.7779620'

      - run: |
          ./sample-android-project/gradlew -p sample-android-project assembleDebug --stacktrace