name: 'build-test'
on:
  pull_request:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: remove android sdk from ubuntu-latest
        shell: bash
        run: |
          echo 'ANDROID_HOME=' >> $GITHUB_ENV
          echo 'ANDROID_SDK_ROOT=' >> $GITHUB_ENV
          rm -rf ~/android

      - name: Setup Android SDK
        uses: amyu/setup-android@59662f715b1a30406b3048059fed17bf76397693
        with:
          is-use-cache: true

      - run: |
          cd sample-android-project
          ./gradlew assembleDebug